    # .github/workflows/node-hello.yml
    name: 2. Node.js Hello World

    on:
      push:
        branches: [ "main" ]
      pull_request:
        branches: [ "main" ]

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v5
          with:
            node-version: '23.x' # Or your desired Node.js version
            
        - name: Run Hello World script
          run: node index.js
          #run:  cd hello-nodejs-actions && node index.js
