    # .github/workflows/node-hello.yml
    name: Node.js Hello World

    on:
      push:
        branches: [ "main" ]
      pull_request:
        branches: [ "main" ]

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '23.x' # Or your desired Node.js version
        - name: Run Hello World script
          run: node index.js

      success:
        runs-on: ubuntu-latest
        needs: build

        steps:
        - name: Success Message
          run: echo "Build and Hello World script ran successfully!"